typography_spectrum: 0.6179477641473312
color:
  brandColors:
    - '#292929'
    - '#656160'
    - '#FDFDFD'
    - '#CFCDCE'
    - '#57B4D3'
  brandStrength: 0.19395247167538815
  lightness: 0.3773114719891939
  saturation: 0.30211365081803265
  rhythmicContrast: 0.9604273165469196
github: true
layout_spectrum: 0.26946372373970134
name: Third Rock
navigation:
  - name: Partners in Crime
    id: 86491170-70f9-44f7-bb47-95d159e01480
    type: content
  - name: Our Rice Bowl
    id: bfd54a2c-06bb-4516-8cf8-a22f59ad6a43
    type: content
  - name: Our Services
    id: aa2b6a4f-15e2-4f36-a7f8-9c9b56038278
    type: content
title: Third Rock
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/85db8b6c-0e65-4343-84eb-010bfe72a4e6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/85db8b6c-0e65-4343-84eb-010bfe72a4e6.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc72df70-372f-4303-a1bf-0dee02e825c0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc72df70-372f-4303-a1bf-0dee02e825c0.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Connect. Collaborate. Create. '
purpose:
  - type: contact
    label: Contact Us
    url: 'mailto:trdrock@gmail.com'
  - type: contact
    label: '+60123857845'
    url: 'tel:+60123857845'
